development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: cosmic_cola_development
  pool: 5
  username:
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: cosmic_cola_test
  pool: 5
  username:
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: cosmic_cola_production
  pool: 5
  username:
  password:
  socket: /tmp/mysql.sock
